### ISSUE TITLE
error when go get -u github.com/PuerkitoBio/gred/...

### ISSUE THREAD

**Issue by Plamen25** [PuerkitoBio/gred#1]
I get the following error:

`package code.google.com/p/go-uuid/uuid: unable to detect version control system for code.google.com /path
`
Please help!

**Comment by PuerkitoBio** [comment]
Hello,

Yeah that repo has been abandoned for the past 2+ years, so a few things may be broken. In this case though it should be a simple matter of renaming the import path to `github.com/pborman/uuid` (that's because code.google.com has shut down).

Hope this helps,
Martin

**Comment by Plamen25** [comment]
Thanks!
